### ISSUE TITLE
Versions 7 & 8

### ISSUE THREAD

**Issue by aytekaman** [maximrouf/All_Vuforia_versions#2]
Hi Maximrouf,

Thanks for keeping these versions, appreciated! Do you have unity packages for versions 7 & 8 by any chance? We are having some compatibility issues and we really like to get access to versions 7 & 8.

Regards,

**Comment by maximrouf** [comment]
Hi. You need to visit Unity.com and there you can download both versions 7.X - 8.X 
(due to partnership agreement between Unity and Vuforia)

For example, open - https://unity3d.com/unity/whats-new/2018.4.25
And there you will see a link to a suitable version of Vuforia.
